# Generated by Django 4.2.3 on 2023-08-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='модерация'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='публикация'),
        ),
    ]
