# Generated by Django 4.2.3 on 2023-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_comments_is_approved_alter_posts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='модерация'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='публикация'),
        ),
    ]
